image: Visual Studio 2017
platform: x64

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'

install:
  - ps: Update-NodeJsInstallation 12.3.0 x64

build_script:
  - npm install

test_script:
  - npm run dist:win
